### ISSUE TITLE
Uncaught TypeError: Unable to watch path

### ISSUE THREAD

**Issue by bartsipes** [Azerothian/atom-sharp#1]
[Enter steps to reproduce below:]
1. Right-click on .xml file
2. Click "Open with Atom"

**Atom Version**: 0.181.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [atom-sharp](https://github.com/azerothian/atom-sharp) package, v0.1.0
### Stack Trace

Uncaught TypeError: Unable to watch path

```
At C:\Users\sipesb\AppData\Local\atom\app-0.181.0\resources\app\src\workspace.js:508

TypeError: Unable to watch path
    at TypeError (native)
    at HandleWatcher.start (C:\Users\sipesb\AppData\Local\atom\app-0.181.0\resources\app\node_modules\pathwatcher\lib\main.js:66:29)
    at new HandleWatcher (C:\Users\sipesb\AppData\Local\atom\app-0.181.0\resources\app\node_modules\pathwatcher\lib\main.js:30:12)
    at new PathWatcher (C:\Users\sipesb\AppData\Local\atom\app-0.181.0\resources\app\node_modules\pathwatcher\lib\main.js:120:30)
    at Object.exports.watch (C:\Users\sipesb\AppData\Local\atom\app-0.181.0\resources\app\node_modules\pathwatcher\lib\main.js:179:12)
    at File.module.exports.File.subscribeToNativeChangeEvents (C:\Users\sipesb\AppData\Local\atom\app-0.181.0\resources\app\node_modules\pathwatcher\lib\file.js:404:109)
    at File.module.exports.File.willAddSubscription (C:\Users\sipesb\AppData\Local\atom\app-0.181.0\resources\app\node_modules\pathwatcher\lib\file.js:108:14)
    at File.willAddSubscription (C:\Users\sipesb\AppData\Local\atom\app-0.181.0\resources\app\node_modules\pathwatcher\lib\file.js:3:61)
    at File.module.exports.File.onDidChange (C:\Users\sipesb\AppData\Local\atom\app-0.181.0\resources\app\node_modules\pathwatcher\lib\file.js:88:12)
    at TextBuffer.module.exports.TextBuffer.subscribeToFile (C:\Users\sipesb\AppData\Local\atom\app-0.181.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1089:44)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus-async, v0.22.0
compare-files, v0.3.1

# Dev
No dev packages
```

**Comment by bartsipes** [comment]
Atom was not open when I went to open the .xml file in Atom.

**Comment by Azerothian** [comment]
@bartsipes i believe this is the wrong repo for this issue, you might want to head over to https://github.com/atom/atom

There is no functionality within this plug-in that monitors a directory or use watch in that fashion
