### ISSUE TITLE
Failed to activate the atom-sharp package

### ISSUE THREAD

**Issue by gtaranas** [Azerothian/atom-sharp#12]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [atom-sharp](https://github.com/azerothian/atom-sharp) package, v0.1.0
### Stack Trace

Failed to activate the atom-sharp package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (C:\Users\Administrator\.atom\packages\atom-sharp\lib\reactView.coffee:1:1)
  at C:\Users\Administrator\.atom\packages\atom-sharp\lib\reactView.coffee:7:3
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-sharp\lib\reactView.coffee:81:5)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-sharp\lib\reactView.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-sharp\lib\solutionView.coffee:2:13)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-sharp\lib\solutionView.coffee:2:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-sharp\lib\index.coffee:14:16)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-sharp\lib\index.coffee:2:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\src\package.js:707:34)
  at Package.module.exports.Package.activateConfig (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\src\package.js:255:12)
  at Package.module.exports.Package.activateNow (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\src\package.js:234:14)
  at C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\src\package.js:770:25
  at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\src\command-registry.js:219:20)
  at CommandRegistry.handleCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\src\command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\src\space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\src\window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\atom.asar\renderer\api\lib\remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\src\window-event-handler.js:148:33)
  at HTMLDocument.handler (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Administrator\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```
### Commands

```
     -1:18.5.0 omnisharp-atom:go-to-implementation (atom-text-editor.editor.is-focused)
     -1:14.2.0 omnisharp-atom:code-format (atom-text-editor.editor.is-focused)
     -1:10.8.0 omnisharp-atom:find-symbols (atom-text-editor.editor.is-focused)
     -1:07.4.0 omnisharp-atom:find-usages (atom-text-editor.editor.is-focused)
     -1:02.7.0 encoding-selector:show (atom-text-editor.editor)
     -0:59.8.0 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:54.7.0 omnisharp-atom:toggle-errors (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:48.5.0 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:46.8.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
atom-sharp, v0.1.0
atom-yeoman, v0.3.6
linter, v0.12.6
omnisharp-atom, v0.12.0

# Dev
No dev packages
```

**Comment by toadicus** [comment]
Can confirm with atom 1.0, atom-sharp 0.1.0.

**Comment by Ghasan** [comment]
I confirm this using Atom 1.0.19 on Windows 10 Pro x64. Just by clicking on 'Sharp -> Open Solution'.

OminSharp 0.25.0.

**Comment by victorperin** [comment]
:+1:
