### ISSUE TITLE
Failed to load the atom-sharp package

### ISSUE THREAD

**Issue by Bomret** [Azerothian/atom-sharp#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.199.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-sharp](https://github.com/azerothian/atom-sharp) package, v0.1.0
### Stack Trace

Failed to load the atom-sharp package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/stefanreichel/.atom/packages/atom-sharp/lib/reactView.coffee:4:199)
    at /Users/stefanreichel/.atom/packages/atom-sharp/lib/reactView.coffee:13:5
    at Object.<anonymous> (/Users/stefanreichel/.atom/packages/atom-sharp/lib/reactView.coffee:81:5)
    at Object.<anonymous> (/Users/stefanreichel/.atom/packages/atom-sharp/lib/reactView.coffee:83:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/stefanreichel/.atom/packages/atom-sharp/lib/solutionView.coffee:6:15)
    at Object.<anonymous> (/Users/stefanreichel/.atom/packages/atom-sharp/lib/solutionView.coffee:40:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-sharp, v0.1.0
language-batch, v0.3.3
language-csharp, v0.5.0
language-fsharp, v0.8.4
language-powershell, v2.0.1
minimap, v4.8.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.3
minimap-selection, v4.2.0

# Dev
No dev packages
```

**Comment by eugene-d** [comment]
Have the same

**Comment by Yoshi325** [comment]
Just received this error.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-sharp](https://github.com/azerothian/atom-sharp) package, v0.1.0

**Comment by nZeus** [comment]
1. Install latest Atom version
2. Try to install atom-sharp

**Atom Version**: 1.1.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-sharp](https://github.com/azerothian/atom-sharp) package, v0.1.0

### Stack Trace

Failed to load the atom-sharp package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (C:\Users\i.tsvetkov\.atom\packages\atom-sharp\lib\reactView.coffee:1:1)
  at C:\Users\i.tsvetkov\.atom\packages\atom-sharp\lib\reactView.coffee:7:3
  at Object.<anonymous> (C:\Users\i.tsvetkov\.atom\packages\atom-sharp\lib\reactView.coffee:81:5)
  at Object.<anonymous> (C:\Users\i.tsvetkov\.atom\packages\atom-sharp\lib\reactView.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\i.tsvetkov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\i.tsvetkov\.atom\packages\atom-sharp\lib\solutionView.coffee:2:13)
  at Object.<anonymous> (C:\Users\i.tsvetkov\.atom\packages\atom-sharp\lib\solutionView.coffee:2:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\i.tsvetkov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\i.tsvetkov\.atom\packages\atom-sharp\lib\index.coffee:14:16)
  at Object.<anonymous> (C:\Users\i.tsvetkov\.atom\packages\atom-sharp\lib\index.coffee:2:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\i.tsvetkov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\i.tsvetkov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:725:34)
  at C:\Users\i.tsvetkov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:176:28
  at Package.module.exports.Package.measure (C:\Users\i.tsvetkov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:153:15)
  at Package.module.exports.Package.load (C:\Users\i.tsvetkov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\i.tsvetkov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\i.tsvetkov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:473:30)
  at C:\Users\i.tsvetkov\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
  at exit (C:\Users\i.tsvetkov\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
  at triggerExitCallback (C:\Users\i.tsvetkov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\i.tsvetkov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
     -2:38 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
     -2:34.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -2:34.5.0 core:delete (atom-text-editor.editor.mini.is-focused)
     -2:29.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:28.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
  2x -2:28.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  4x -2:20.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "less-compiler"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-sharp, v0.1.0
less-autocompile, v1.0.0

# Dev
No dev packages
```

**Comment by Clpsplug** [comment]
[Enter steps to reproduce below:]
1. The error just started popping up every time I open Atom.

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-sharp](https://github.com/azerothian/atom-sharp) package, v0.1.0

### Stack Trace

Failed to load the atom-sharp package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/CPlug/.atom/packages/atom-sharp/lib/reactView.coffee:1:1)
    at /Users/CPlug/.atom/packages/atom-sharp/lib/reactView.coffee:7:3
    at Object.<anonymous> (/Users/CPlug/.atom/packages/atom-sharp/lib/reactView.coffee:7:3)
    at Object.<anonymous> (/Users/CPlug/.atom/packages/atom-sharp/lib/reactView.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/CPlug/.atom/packages/atom-sharp/lib/solutionView.coffee:2:13)
    at Object.<anonymous> (/Users/CPlug/.atom/packages/atom-sharp/lib/solutionView.coffee:2:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-sharp, v0.1.0

# Dev
No dev packages
```

**Comment by wuxingogo** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-sharp](https://github.com/azerothian/atom-sharp) package, v0.1.0

### Stack Trace

Failed to load the atom-sharp package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/ly-user/.atom/packages/atom-sharp/lib/reactView.coffee:1:1)
    at /Users/ly-user/.atom/packages/atom-sharp/lib/reactView.coffee:7:3
    at Object.<anonymous> (/Users/ly-user/.atom/packages/atom-sharp/lib/reactView.coffee:7:3)
    at Object.<anonymous> (/Users/ly-user/.atom/packages/atom-sharp/lib/reactView.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Users/ly-user/Documents/SoftWare/atom/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ly-user/.atom/packages/atom-sharp/lib/solutionView.coffee:2:13)
    at Object.<anonymous> (/Users/ly-user/.atom/packages/atom-sharp/lib/solutionView.coffee:2:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Users/ly-user/Documents/SoftWare/atom/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ly-user/.atom/packages/atom-sharp/lib/index.coffee:14:16)
    at Object.<anonymous> (/Users/ly-user/.atom/packages/atom-sharp/lib/index.coffee:2:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Users/ly-user/Documents/SoftWare/atom/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (/Users/ly-user/Documents/SoftWare/atom/Atom.app/Contents/Resources/app.asar/src/package.js:661:34)
    at /Users/ly-user/Documents/SoftWare/atom/Atom.app/Contents/Resources/app.asar/src/package.js:115:28
    at Package.module.exports.Package.measure (/Users/ly-user/Documents/SoftWare/atom/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Users/ly-user/Documents/SoftWare/atom/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Users/ly-user/Documents/SoftWare/atom/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/ly-user/Documents/SoftWare/atom/Atom.app/Contents/Resources/app.asar/src/package-manager.js:511:30)
    at /Users/ly-user/Documents/SoftWare/atom/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Users/ly-user/Documents/SoftWare/atom/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Users/ly-user/Documents/SoftWare/atom/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Users/ly-user/Documents/SoftWare/atom/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/Users/ly-user/Documents/SoftWare/atom/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -7:28.3.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -6:56.5.0 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused)
     -6:39.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:16.4.0 activate-power-mode:toggle (atom-text-editor.editor.is-focused)
     -6:14.2.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused.power-mode)
  4x -6:12.7.0 core:backspace (atom-text-editor.editor.is-focused.power-mode)
  3x -6:08.9.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused.power-mode)
     -6:06.4.0 core:close (atom-text-editor.editor.is-focused.power-mode)
  2x -1:20.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
activate-power-mode, v0.3.2
atom-sharp, v0.1.0

# Dev
No dev packages
```

**Comment by Danielmelody** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11
**Thrown From**: [atom-sharp](https://github.com/azerothian/atom-sharp) package, v0.1.0

### Stack Trace

Failed to load the atom-sharp package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/huyiming/.atom/packages/atom-sharp/lib/reactView.coffee:1:1)
    at /Users/huyiming/.atom/packages/atom-sharp/lib/reactView.coffee:7:3
    at Object.<anonymous> (/Users/huyiming/.atom/packages/atom-sharp/lib/reactView.coffee:7:3)
    at Object.<anonymous> (/Users/huyiming/.atom/packages/atom-sharp/lib/reactView.coffee:1:1)
    at Module._compile (/Applications/Atom 2.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom 2.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom 2.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/huyiming/.atom/packages/atom-sharp/lib/solutionView.coffee:2:13)
    at Object.<anonymous> (/Users/huyiming/.atom/packages/atom-sharp/lib/solutionView.coffee:2:1)
    at Module._compile (/Applications/Atom 2.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom 2.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom 2.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/huyiming/.atom/packages/atom-sharp/lib/index.coffee:14:16)
    at Object.<anonymous> (/Users/huyiming/.atom/packages/atom-sharp/lib/index.coffee:2:1)
    at Module._compile (/Applications/Atom 2.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom 2.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom 2.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom 2.app/Contents/Resources/app.asar/src/package.js:721:27)
    at /Applications/Atom 2.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom 2.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom 2.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom 2.app/Contents/Resources/app.asar/src/package-manager.js:443:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom 2.app/Contents/Resources/app.asar/src/package-manager.js:393:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom 2.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom 2.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom%202.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom%202.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-clang",
      "nuclide-format-js",
      "linter-js-standard",
      "clang-format",
      "omnisharp-atom"
    ],
    "ignoredNames": [
      "*.meta",
      "*.DS_Store",
      ".git",
      "*.sln",
      "*.csproj",
      "*.vsproj"
    ],
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-material-ui, v0.8.0
atom-sharp, v0.1.0
atom-typescript, v7.11.1
atom-yeoman, v0.3.15
autocomplete-glsl, v0.2.3
autocomplete-webgl, v1.1.0
build-make, v0.7.0
console-log, v0.8.3
css-snippets, v0.9.0
json-schema, v0.1.15
language-cmake, v0.1.4
language-glsl, v2.0.1
language-lua, v0.9.4
linter, v1.11.2
linter-cpplint, v1.0.0
linter-gcc, v0.5.0
linter-lua, v1.0.0
nuclide-code-format, v0.0.35
pretty-json, v0.4.1
space-tab, v0.4.2
unity-shader-files, v0.1.0

# Dev
No dev packages
```

**Comment by caiodias** [comment]
I have the same error.

**Comment by vernichon** [comment]
I have the same error.

**Comment by caiodias** [comment]
I solved this problem just removing this package. Uninstall it.
